### ISSUE TITLE
Self provisioner can't see its devops project

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2563]
**Describe the Bug**
A self provisioner creates a new devops project. It does not show in the list, but when I switch to the admin of the workspace. The devops project is actually created.
![Screen Shot 2020-07-23 at 5 38 22 PM](https://user-images.githubusercontent.com/28859385/88272688-ae403800-cd0b-11ea-9075-d18008c20d4b.png)
 
![Screen Shot 2020-07-23 at 5 39 13 PM](https://user-images.githubusercontent.com/28859385/88272733-c021db00-cd0b-11ea-89df-3053b989c01b.png)

**Versions Used**
KubeSphere: 3.0.0-dev
Kubernetes: 1.18.6

**Environment**
allinone with devops enabled

**Expected behavior**
Self provisioner can see its devops project

**Comment by harrisonliu5** [comment]
it has fixed in #[#985](https://github.com/kubesphere/console/pull/985)

**Comment by rayzhou2017** [comment]
Not fixed yet. The weird thing is when I create the first devops project, although it is not auto refrest, I can manually refresh the page to see it in the list page. But when I create the second devops project, I can't see the new one. Using the admin of the ws can see all devops project.

**Comment by rayzhou2017** [comment]
verified
