### ISSUE TITLE
Can't upload version in application template

### ISSUE THREAD

**Issue by Ironeie** [kubesphere/kubesphere#6258]
**Describe the Bug**
Can't upload version in application template
There is no response when clicking (Application Management – ​​Application Template – Upload Version). There is no log output.
The same as https://ask.kubesphere.io/forum/d/23946-v411-dian-ji-ying-yong-guan-li-ying-yong-mo-ban-shang-chuan-ban-ben-shi-mei-you-fan-ying

**Versions Used**
KubeSphere: v4.1.2
Kubernetes: v1.29.7

**Environment**
How many nodes and their hardware configuration:

Ubuntu 22.04 / 3 masters:  64cpu/128g

**Comment by inksnw** [comment]
Will tracked here
https://github.com/kubesphere/project/issues/4815

**Comment by Ironeie** [comment]
But my chrome console doesn't produce error, it's just a warning "doculentClick时间订阅数量为空 undefined", which is perhaps not the same problem?

**Comment by mike-pisman** [comment]
I am also having this issue. The button dose not do anything

Kubernetes version v1.31.4
CHART: ks-core
VERSION: 1.1.3
APP_VERSION: v4.1.2

**Comment by cwchiu** [comment]
I am also having this issue. The button dose not do anything

Kubernetes version v1.30.10
CHART: ks-core
VERSION: 1.1.5
APP_VERSION: v4.1.3

**Comment by zhou1203** [comment]
This issue has been fixed by the openpitrix-v2.0.2, .
You can get the release at https://github.com/kubesphere-extensions/ks-extensions/releases/tag/v1.1.6 .

**Comment by cwchiu** [comment]
@zhou1203 

I have upgraded to 2.0.2 and the problem still exists.

![Image](https://github.com/user-attachments/assets/fdbdd4e4-9119-4e6d-a28a-d2524c2e13c8)

![Image](https://github.com/user-attachments/assets/6c786ba9-a8da-46d6-919a-fe9a27cf6aeb)

**Comment by cwchiu** [comment]
I may have found my problem. If you click Update directly, docker.io/kubesphere/apps-manage doesn't seem to use 2.0.2.

Edit Config and it works fine.
 
![Image](https://github.com/user-attachments/assets/29e9a494-10fd-4b11-abae-4c9f49c33777)

But why does the new version of the previous yaml app only work with .tgz? 

![Image](https://github.com/user-attachments/assets/071ad165-a447-4181-b09b-ae921279fb75)
